# Generated by Django 4.2.5 on 2023-10-09 21:21

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alaris', '0002_alter_product_product_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='new', max_length=50)),
                ('hlr_provider', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('msisdn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=20)),
                ('result', models.IntegerField()),
                ('mcc', models.CharField(blank=True, max_length=3, null=True)),
                ('mnc', models.CharField(blank=True, max_length=3, null=True)),
                ('ported', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('http_error_code', models.IntegerField()),
                ('hlr_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alaris.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hlr.task')),
            ],
        ),
    ]
