# Generated by Django 4.2.5 on 2023-10-20 08:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hlr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='new', max_length=50)),
                ('external_product_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, validators=[hlr.models.validate_alaris_product_id])),
                ('msisdn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=20)),
                ('result', models.IntegerField()),
                ('mccmnc', models.CharField(blank=True, max_length=6, null=True)),
                ('ported', models.CharField(max_length=10)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('http_error_code', models.IntegerField()),
                ('external_product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='alaris.product', to_field='external_product_id')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='hlr.task')),
            ],
        ),
    ]
