# Generated by Django 4.2.5 on 2023-11-06 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import hlr.parser.hlr_parser


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='new', max_length=50)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-insert_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(default='new', max_length=50)),
                ('request_id', models.CharField(null=True)),
                ('msisdn', models.CharField(max_length=20)),
                ('result', models.IntegerField(null=True)),
                ('mccmnc', models.CharField(blank=True, max_length=6, null=True)),
                ('ported', models.BooleanField(null=True)),
                ('roaming', models.BooleanField(null=True)),
                ('presents', models.BooleanField(null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('http_error_code', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='alaris.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='hlr.task')),
            ],
        ),
        migrations.CreateModel(
            name='HlrProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TMT_HLR', hlr.parser.hlr_parser.HlrParserType['TMT_HLR']), ('INFOBIP_HLR', hlr.parser.hlr_parser.HlrParserType['INFOBIP_HLR']), ('XCONNECT_HLR', hlr.parser.hlr_parser.HlrParserType['XCONNECT_HLR']), ('XCONNECT_MNP', hlr.parser.hlr_parser.HlrParserType['XCONNECT_MNP'])])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='hlr', to='alaris.product')),
            ],
        ),
    ]
