# Generated by Django 4.2.5 on 2023-10-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-insert_time']},
        ),
    ]
