# Generated by Django 4.2.5 on 2023-10-21 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alaris', '0001_initial'),
        ('hlr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HlrProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'TMT_HLR'), (2, 'INFOBIP_HLR'), (3, 'XCONNECT_HLR'), (4, 'XCONNECT_MNP')])),
                ('external_product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='alaris.product', to_field='external_product_id')),
            ],
        ),
    ]
