# Generated by Django 4.2.5 on 2023-10-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0002_hlrproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hlrproduct',
            name='type',
        ),
    ]
