# Generated by Django 4.2.5 on 2024-03-13 09:08

from django.db import migrations, models
import hlr.parser.hlr_parser


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0002_taskdetail_insert_time_taskdetail_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlrproduct',
            name='type',
            field=models.CharField(choices=[('TMT_HLR', hlr.parser.hlr_parser.HlrParserType['TMT_HLR']), ('INFOBIP_HLR', hlr.parser.hlr_parser.HlrParserType['INFOBIP_HLR']), ('XCONNECT_HLR', hlr.parser.hlr_parser.HlrParserType['XCONNECT_HLR']), ('XCONNECT_MNP', hlr.parser.hlr_parser.HlrParserType['XCONNECT_MNP']), ('MITTO_HLR', hlr.parser.hlr_parser.HlrParserType['MITTO_HLR']), ('TYNTEC_HLR', hlr.parser.hlr_parser.HlrParserType['TYNTEC_HLR']), ('NETNUMBER_HLR', hlr.parser.hlr_parser.HlrParserType['NETNUMBER_HLR'])]),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='message',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
