# Generated by Django 4.2.5 on 2023-10-10 10:11

import django.contrib.postgres.fields
from django.db import migrations, models

import hlr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0002_alter_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alaris_product_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, validators=[hlr.models.validate_alaris_product_id]),
        ),
    ]
