# Generated by Django 4.2.5 on 2023-10-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0003_alter_task_alaris_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='hlr.task'),
        ),
    ]
