# Generated by Django 4.2.5 on 2023-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0004_hlrproduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlrproduct',
            name='type',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
