# Generated by Django 4.2.5 on 2023-10-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0006_alter_hlrproduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlrproduct',
            name='type',
            field=models.CharField(choices=[(1, 'HlrParserType.TMT_HLR'), (2, 'HlrParserType.INFOBIP_HLR'), (3, 'HlrParserType.XCONNECT_HLR'), (4, 'HlrParserType.XCONNECT_MNP')]),
        ),
    ]
