# Generated by Django 4.2.5 on 2023-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0007_alter_hlrproduct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlrproduct',
            name='type',
            field=models.CharField(choices=[('TMT_HLR', 'TMT_HLR'), ('INFOBIP_HLR', 'INFOBIP_HLR'), ('XCONNECT_HLR', 'XCONNECT_HLR'), ('XCONNECT_MNP', 'XCONNECT_MNP')]),
        ),
    ]
