# Generated by Django 4.2.5 on 2023-10-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alaris', '0001_initial'),
        ('hlr', '0011_alter_hlrproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlrproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='hlr', to='alaris.product', to_field='external_product_id'),
        ),
    ]
