# Generated by Django 4.2.5 on 2023-10-24 20:13

from django.db import migrations, models
import hlr.parser.hlr_parser


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0012_alter_hlrproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlrproduct',
            name='type',
            field=models.CharField(choices=[('TMT_HLR', hlr.parser.hlr_parser.HlrParserType['TMT_HLR']), ('INFOBIP_HLR', hlr.parser.hlr_parser.HlrParserType['INFOBIP_HLR']), ('XCONNECT_HLR', hlr.parser.hlr_parser.HlrParserType['XCONNECT_HLR']), ('XCONNECT_MNP', hlr.parser.hlr_parser.HlrParserType['XCONNECT_MNP'])]),
        ),
    ]
