# Generated by Django 4.2.5 on 2023-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0013_alter_hlrproduct_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='presents',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='roaming',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='ported',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
