# Generated by Django 4.2.5 on 2023-10-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0014_taskdetail_presents_taskdetail_roaming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='ported',
            field=models.BooleanField(),
        ),
    ]
