# Generated by Django 4.2.5 on 2023-10-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0015_alter_taskdetail_ported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='ported',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='presents',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='roaming',
            field=models.BooleanField(null=True),
        ),
    ]
