# Generated by Django 4.2.5 on 2023-10-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlr', '0016_alter_taskdetail_ported_alter_taskdetail_presents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='request_id',
            field=models.CharField(null=True),
        ),
    ]
