version: '3'

services:
  django:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "
              python manage.py collectstatic --noinput 
              && gunicorn tech_service.wsgi:application  -w ${WORKER_COUNT} -b :${APP_PORT}"
  migration:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: python manage.py migrate
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    healthcheck:
      test:  [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
