#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mkdir -p static
mkdir -p media
python manage.py collectstatic --noinput
python manage.py migrate

exec gunicorn tech_service.wsgi:application  -w 2 -b :8000
