# Generated by Django 4.2.5 on 2023-09-21 21:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alaris_car_id', models.PositiveIntegerField()),
                ('car_name', models.CharField(max_length=120)),
                ('car_is_active', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alaris_product_type_id', models.PositiveIntegerField()),
                ('type_name', models.CharField(max_length=120)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alaris_product_id', models.PositiveIntegerField()),
                ('acc_currency_code', models.CharField(max_length=10)),
                ('alaris_acc_id', models.PositiveIntegerField()),
                ('is_active', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('product_caption', models.CharField(max_length=150)),
                ('product_description', models.CharField(max_length=60)),
                ('product_direction', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1)])),
                ('product_notes', models.CharField(max_length=120, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='alaris.carrier')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='alaris.producttype')),
            ],
        ),
    ]
