# Generated by Django 4.2.5 on 2023-10-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='carrier_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='carrier_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_direction',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='type_name',
            new_name='name',
        ),
    ]
